spring.application.name=api-vendas

# Configuracao do banco de dados MySQL - Producao
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/hanami_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:false}
spring.jpa.database-platform=${SPRING_JPA_DATABASE_PLATFORM:org.hibernate.dialect.MySQLDialect}

# Swagger/OpenAPI
springdoc.api-docs.path=/docs
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

spring.servlet.multipart.max-file-size=5MB

# Configuracoes de logging - Producao
logging.file.name=logs/app.log
logging.level.root=INFO
logging.level.com.recode.hanami=INFO
logging.level.org.springframework.web=WARN

logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n

logging.logback.rollingpolicy.max-file-size=100MB
logging.logback.rollingpolicy.max-history=7